<?php
/**
 * @file
 * Code for the DrupalCamp Ottawa feature.
 */

include_once 'drupalcamp_ottawa.features.inc';

/**
 * Implements hook_menu_alter().
 */
function drupalcamp_ottawa_menu_alter(&$items) {

  // Example - disable the page at node/add
  $items['user/register']['title'] = 'Register';
  $items['user/register']['menu_name'] = 'user-menu';
  $items['user/register']['weight'] = -50;
  $items['user/register']['type'] = MENU_NORMAL_ITEM;
}

/**
 * Implements hook_menu().
 */
function drupalcamp_ottawa_menu() {
  $items['user/login'] = array(
    'title' => 'Log in',
    'access callback' => 'user_is_anonymous',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'user-menu',
  );

  return $items;
}
